// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/getSms/getSms.proto

package go_micro_srv_getSms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc7149810825cbb, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type Request struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Uuid                 string   `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc7149810825cbb, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Request) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Response struct {
	Errmsg               string   `protobuf:"bytes,1,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Errno                string   `protobuf:"bytes,2,opt,name=errno,proto3" json:"errno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc7149810825cbb, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.getSms.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.getSms.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.getSms.Response")
}

func init() { proto.RegisterFile("proto/getSms/getSms.proto", fileDescriptor_5dc7149810825cbb) }

var fileDescriptor_5dc7149810825cbb = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x8a, 0xc2, 0x30,
	0x14, 0x85, 0xa7, 0xf3, 0xd3, 0x4e, 0xef, 0xec, 0x32, 0x22, 0x55, 0x14, 0x24, 0x2b, 0x57, 0x11,
	0x74, 0xe3, 0x1b, 0x88, 0x60, 0x37, 0x15, 0xdc, 0x5b, 0xbd, 0x84, 0x82, 0x69, 0x6a, 0x6e, 0x2a,
	0x3e, 0xbe, 0xe4, 0xc7, 0x9d, 0xae, 0x72, 0xcf, 0x77, 0xe0, 0xf0, 0x11, 0x18, 0x75, 0x46, 0x5b,
	0xbd, 0x90, 0x68, 0xf7, 0x8a, 0xe2, 0x23, 0x3c, 0x63, 0xff, 0x52, 0x0b, 0xd5, 0x9c, 0x8c, 0x16,
	0x64, 0x6e, 0x22, 0x54, 0x3c, 0x87, 0xac, 0x44, 0xa2, 0xa3, 0x44, 0xbe, 0x85, 0xac, 0xc2, 0x6b,
	0x8f, 0x64, 0xd9, 0x10, 0x52, 0xa5, 0xeb, 0xe6, 0x82, 0x45, 0x32, 0x4b, 0xe6, 0x79, 0x15, 0x13,
	0x63, 0xf0, 0x6d, 0xf1, 0x6e, 0x8b, 0x4f, 0x4f, 0xfd, 0xed, 0x58, 0xdf, 0x37, 0xe7, 0xe2, 0x2b,
	0x30, 0x77, 0xf3, 0x35, 0xfc, 0x56, 0x48, 0x9d, 0x6e, 0x09, 0xdd, 0x16, 0x1a, 0xa3, 0x48, 0x3e,
	0xb7, 0x42, 0x62, 0x03, 0xf8, 0x41, 0x63, 0x5a, 0x1d, 0xc7, 0x42, 0x58, 0x1e, 0x20, 0xdd, 0x78,
	0x33, 0xb6, 0x83, 0xbf, 0xd2, 0xd9, 0xc6, 0x38, 0x11, 0x2f, 0xf4, 0x45, 0x14, 0x1e, 0x4f, 0xdf,
	0xb4, 0xc1, 0x81, 0x7f, 0xd4, 0xa9, 0xff, 0x83, 0xd5, 0x23, 0x00, 0x00, 0xff, 0xff, 0x36, 0x4f,
	0x1c, 0xa1, 0x20, 0x01, 0x00, 0x00,
}
