// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getSms/getSms.proto

package go_micro_srv_getSms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GetSms service

type GetSmsService interface {
	MicroGetSms(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type getSmsService struct {
	c    client.Client
	name string
}

func NewGetSmsService(name string, c client.Client) GetSmsService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.getSms"
	}
	return &getSmsService{
		c:    c,
		name: name,
	}
}

func (c *getSmsService) MicroGetSms(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetSms.MicroGetSms", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetSms service

type GetSmsHandler interface {
	MicroGetSms(context.Context, *Request, *Response) error
}

func RegisterGetSmsHandler(s server.Server, hdlr GetSmsHandler, opts ...server.HandlerOption) error {
	type getSms interface {
		MicroGetSms(ctx context.Context, in *Request, out *Response) error
	}
	type GetSms struct {
		getSms
	}
	h := &getSmsHandler{hdlr}
	return s.Handle(s.NewHandler(&GetSms{h}, opts...))
}

type getSmsHandler struct {
	GetSmsHandler
}

func (h *getSmsHandler) MicroGetSms(ctx context.Context, in *Request, out *Response) error {
	return h.GetSmsHandler.MicroGetSms(ctx, in, out)
}
