// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/RegAndLog/RegAndLog.proto

package go_micro_srv_RegAndLog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_6168bb691006bd0e, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type Request struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Smscode              string   `protobuf:"bytes,3,opt,name=smscode,proto3" json:"smscode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_6168bb691006bd0e, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Request) GetSmscode() string {
	if m != nil {
		return m.Smscode
	}
	return ""
}

type Response struct {
	Errno                string   `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_6168bb691006bd0e, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.RegAndLog.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.RegAndLog.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.RegAndLog.Response")
}

func init() { proto.RegisterFile("proto/RegAndLog/RegAndLog.proto", fileDescriptor_6168bb691006bd0e) }

var fileDescriptor_6168bb691006bd0e = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x09, 0x7f, 0x9a, 0xe6, 0xc4, 0x74, 0x42, 0x55, 0xd4, 0xa5, 0x55, 0x26, 0x26, 0x23,
	0xc1, 0x13, 0xb0, 0xa7, 0x12, 0x32, 0x03, 0x73, 0xda, 0x9c, 0x2c, 0x4b, 0xd8, 0x17, 0xee, 0x02,
	0xbc, 0x17, 0x4f, 0x88, 0xea, 0x3a, 0x61, 0x81, 0x8d, 0xed, 0x7e, 0xfa, 0xac, 0x9f, 0xef, 0xd3,
	0xc1, 0x66, 0x10, 0x1e, 0xf9, 0xce, 0x92, 0x7b, 0x8c, 0x7d, 0xcb, 0xee, 0x67, 0x32, 0x29, 0xc1,
	0x95, 0x63, 0x13, 0xfc, 0x41, 0xd8, 0xa8, 0x7c, 0x98, 0x39, 0x6d, 0x2a, 0x28, 0x77, 0xa4, 0xda,
	0x39, 0x6a, 0x5e, 0xa0, 0xb4, 0xf4, 0xf6, 0x4e, 0x3a, 0xe2, 0x0a, 0x16, 0x81, 0xf7, 0xfe, 0x95,
	0xea, 0x62, 0x5b, 0xdc, 0x56, 0x36, 0x13, 0xae, 0x61, 0x39, 0x74, 0xaa, 0x9f, 0x2c, 0x7d, 0x7d,
	0x9e, 0x92, 0x99, 0xb1, 0x86, 0x52, 0x83, 0x1e, 0xb8, 0xa7, 0xfa, 0x22, 0x45, 0x13, 0x36, 0x2d,
	0x2c, 0x2d, 0xe9, 0xc0, 0x51, 0x09, 0x6f, 0xe0, 0x8a, 0x44, 0x22, 0x67, 0xf1, 0x09, 0x8e, 0xff,
	0x91, 0x48, 0x50, 0x97, 0xad, 0x99, 0x10, 0xe1, 0x32, 0x76, 0x61, 0x12, 0xa6, 0xf9, 0xfe, 0xab,
	0x80, 0x6a, 0xde, 0x1f, 0x9f, 0xe1, 0x7a, 0xe7, 0x85, 0x2d, 0x39, 0xaf, 0x23, 0x09, 0x6e, 0xcc,
	0xef, 0x45, 0x4d, 0xae, 0xb6, 0xde, 0xfe, 0xfd, 0xe0, 0xb4, 0x62, 0x73, 0x86, 0x4f, 0x50, 0x1d,
	0xa5, 0x2d, 0x3b, 0x1f, 0xff, 0xc5, 0xb8, 0x5f, 0xa4, 0x2b, 0x3c, 0x7c, 0x07, 0x00, 0x00, 0xff,
	0xff, 0xe1, 0xc9, 0xb0, 0x9a, 0xa8, 0x01, 0x00, 0x00,
}
