// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/RegAndLog/RegAndLog.proto

package go_micro_srv_RegAndLog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for RegAndLog service

type RegAndLogService interface {
	MiroRegister(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	MiroLogin(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type regAndLogService struct {
	c    client.Client
	name string
}

func NewRegAndLogService(name string, c client.Client) RegAndLogService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.RegAndLog"
	}
	return &regAndLogService{
		c:    c,
		name: name,
	}
}

func (c *regAndLogService) MiroRegister(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "RegAndLog.MiroRegister", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regAndLogService) MiroLogin(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "RegAndLog.MiroLogin", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RegAndLog service

type RegAndLogHandler interface {
	MiroRegister(context.Context, *Request, *Response) error
	MiroLogin(context.Context, *Request, *Response) error
}

func RegisterRegAndLogHandler(s server.Server, hdlr RegAndLogHandler, opts ...server.HandlerOption) error {
	type regAndLog interface {
		MiroRegister(ctx context.Context, in *Request, out *Response) error
		MiroLogin(ctx context.Context, in *Request, out *Response) error
	}
	type RegAndLog struct {
		regAndLog
	}
	h := &regAndLogHandler{hdlr}
	return s.Handle(s.NewHandler(&RegAndLog{h}, opts...))
}

type regAndLogHandler struct {
	RegAndLogHandler
}

func (h *regAndLogHandler) MiroRegister(ctx context.Context, in *Request, out *Response) error {
	return h.RegAndLogHandler.MiroRegister(ctx, in, out)
}

func (h *regAndLogHandler) MiroLogin(ctx context.Context, in *Request, out *Response) error {
	return h.RegAndLogHandler.MiroLogin(ctx, in, out)
}
